language: node_js
node_js:
- node

cache:
  bundler: true
  yarn: true
  directories:
  - node_modules
  - vendor/bundle
  - $HOME/.rvm/user/installs

before_install:
- if [[ ! -d $HOME/.rvm/user/installs ]]; then rvm install ruby-2.3.1; fi
- rvm use 2.3.1
- bundle install --deployment

before_script:
- export PATH="$(yarn bin):$PATH"

script:
- gulp lint
- gulp compile --env production
- bundle exec htmlproofer ./_site --check-favicon --check-html --check-external-hash --check-html --check-img-http --check-opengraph

notifications:
  email: false
