---
title: S.B. Decking and Planters
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  projects:
    title: Projects
    output: true
    permalink: "/projects/:title/"
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: projects
  values:
    layout: project
    hide_intro: true
    images:
    - 
    size: 
    testimonial: 
name: S.B. Decking and Planters
email: stevebealing.decking@gmail.com
tel: 07712 804670
description: Steve Bealing is an independent contractor, designing and building bespoke
  decking and garden fixtures across the South West.
headline: Steve Bealing is an independent contractor, designing and building bespoke
  decking and garden fixtures across the South West.
baseurl: "/"
url: https://sbdecking.com
facebook_username: SBdeckingandplanters
author: James Dinsdale
permalink: "/writing/:title/"
pagination:
  enabled: true
  per_page: 5
  permalink: "/:num/"
  sort_reverse: true
markdown: redcarpet
redcarpet:
  extensions:
  - no_intra_emphasis
  - tables
  - autolink
  - strikethrough
  - with_toc_data
  - smart
gems:
- jekyll-feed
- jekyll-sitemap
keep_files:
- css
- js
- img
include:
- _redirects
exclude:
- _assets
- coffeelint.json
- Gemfile
- Gemfile.lock
- gulpfile.coffee
- netlify.toml
- node_modules
- package.json
- yarn.lock
picture:
  source: _uploads
  output: uploads
  markup: picture
  presets:
    default:
      ppi:
      - 1
      - 2
      source_large:
        media: "(min-width: 64em)"
        width: 1280
      source_medium:
        media: "(min-width: 40em)"
        width: 960
      source_default:
        width: 600
